version: '3'

services:
    nginx:
        image: nginx:latest
        volumes:
            - ./:/var/www
            - ./_docker/nginx/conf.d/:/etc/nginx/conf.d
        ports:
            - 9027:80
        container_name: ${CONTAINER_PREFIX}_nginx
        depends_on:
            - app
    app:
        build:
            context: .
            dockerfile: _docker/app/Dockerfile
        volumes:
            - ./:/var/www/
        container_name: ${CONTAINER_PREFIX}_app
        depends_on:
            - db
    db:
        image: postgres:latest
        restart: always
        environment:
            POSTGRES_DB: '${DB_DATABASE}'
            POSTGRES_USER: '${DB_USERNAME}'
            POSTGRES_PASSWORD: '${DB_PASSWORD}'
        volumes:
            - pgdata:/var/lib/postgresql/data
        ports:
            - 5451:5432
        container_name: ${CONTAINER_PREFIX}_db
    test_db:
        image: postgres:latest
        restart: always
        environment:
          POSTGRES_DB: '${DB_DATABASE}'
          POSTGRES_USER: '${DB_USERNAME}'
          POSTGRES_PASSWORD: '${DB_PASSWORD}'
        ports:
          - 5452:5432
        container_name: ${CONTAINER_PREFIX}_test_db
volumes:
    pgdata:
